# Generated by Django 5.1.2 on 2026-03-19 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='storage_node',
        ),
        migrations.CreateModel(
            name='ChunkReplica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replicas', to='core.chunk')),
                ('storage_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replicas', to='core.storagenode')),
            ],
            options={
                'unique_together': {('chunk', 'storage_node')},
            },
        ),
    ]
