# Generated by Django 5.1.2 on 2026-04-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chunk_expected_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplicatedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.BigIntegerField(unique=True)),
                ('op_id', models.UUIDField(unique=True)),
                ('op_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
