events {}

http {
    server {
        listen 7000;

        location /node3/ {
            rewrite ^/node3/(.*) /$1 break;
            proxy_pass http://host.docker.internal:6000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /node4/ {
            rewrite ^/node4/(.*) /$1 break;
            proxy_pass http://host.docker.internal:6001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
