events {}

http {
    server {
        listen 7001;

        location /node1/ {
            rewrite ^/node1/(.*) /$1 break;
            proxy_pass http://host.docker.internal:6000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /node2/ {
            rewrite ^/node2/(.*) /$1 break;
            proxy_pass http://host.docker.internal:6001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
