version: "3.9"

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - cps559_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  main-server:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      # - AWS_ACCESS_KEY_ID=minioadmin
      # - AWS_SECRET_ACCESS_KEY=minioadmin123
      # - AWS_S3_ENDPOINT_URL=http://minio:9000
      # - S3_BUCKET_NAME=maple-quest-images
    networks:
      - cps559_network
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data:

networks:
  cps559_network:
    external: true
